### ISSUE TITLE
Shouldn't the data node be included for each relationship?

### ISSUE THREAD

**Issue by krzkrzkrz** [endpoints/example#21]
At `http://localhost:8080/v1/authors/1/books`

Shouldnt the relationship nodes (i.e. `chapters,`firstChapter`,`series`) have the`data` node for each

**Comment by tkellen** [comment]
Data is optional. You'll see it populated on to-one relationships pretty much always because that data is a part of the resource being requested (author is a representation of the author_id field, for example). For to-many relationships there is no data available to put there unless the relationship has been included.
